//
// File generated by rootcint at Mon Aug  1 15:25:49 2011

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME Mydict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Mydict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::Alumno Alumno;
      #else
      class Alumno  {
         public:
         //friend XX;
         int edad; //
         string* nombre; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Alumno_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void Alumno_Dictionary();
   static void *new_Alumno(void *p = 0);
   static void *newArray_Alumno(Long_t size, void *p);
   static void delete_Alumno(void *p);
   static void deleteArray_Alumno(void *p);
   static void destruct_Alumno(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Alumno*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::Alumno) == sizeof(::ROOT::Shadow::Alumno));
      ::Alumno *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::Alumno),0);
      static ::ROOT::TGenericClassInfo 
         instance("Alumno", "./Alumno.h", 11,
                  typeid(::Alumno), DefineBehavior(ptr, ptr),
                  &Alumno_ShowMembers, &Alumno_Dictionary, isa_proxy, 4,
                  sizeof(::Alumno) );
      instance.SetNew(&new_Alumno);
      instance.SetNewArray(&newArray_Alumno);
      instance.SetDelete(&delete_Alumno);
      instance.SetDeleteArray(&deleteArray_Alumno);
      instance.SetDestructor(&destruct_Alumno);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Alumno*)
   {
      return GenerateInitInstanceLocal((::Alumno*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Alumno*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void Alumno_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::Alumno*)0x0)->GetClass();
   }

} // end of namespace ROOT

//______________________________________________________________________________
namespace ROOT {
   void Alumno_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class Alumno.
      typedef ::ROOT::Shadow::Alumno ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOT::GenerateInitInstanceLocal((const ::Alumno*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "edad", &sobj->edad);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*nombre", &sobj->nombre);
   }

}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Alumno(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Alumno : new ::Alumno;
   }
   static void *newArray_Alumno(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::Alumno[nElements] : new ::Alumno[nElements];
   }
   // Wrapper around operator delete
   static void delete_Alumno(void *p) {
      delete ((::Alumno*)p);
   }
   static void deleteArray_Alumno(void *p) {
      delete [] ((::Alumno*)p);
   }
   static void destruct_Alumno(void *p) {
      typedef ::Alumno current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Alumno

/********************************************************
* Mydict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableMydict();

extern "C" void G__set_cpp_environmentMydict() {
  G__cpp_reset_tagtableMydict();
}
#include <new>
extern "C" int G__cpp_dllrevMydict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Alumno */
static int G__Mydict_160_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Alumno* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Alumno[n];
     } else {
       p = new((void*) gvp) Alumno[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Alumno;
     } else {
       p = new((void*) gvp) Alumno;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MydictLN_Alumno));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Mydict_160_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Alumno* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 2
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Alumno((int) G__int(libp->para[0]), *((string*) G__int(libp->para[1])));
   } else {
     p = new((void*) gvp) Alumno((int) G__int(libp->para[0]), *((string*) G__int(libp->para[1])));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MydictLN_Alumno));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Mydict_160_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Alumno*) G__getstructoffset())->ver();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Mydict_160_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Alumno* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Alumno(*(Alumno*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MydictLN_Alumno));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Alumno G__TAlumno;
static int G__Mydict_160_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Alumno*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Alumno*) (soff+(sizeof(Alumno)*i)))->~G__TAlumno();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Alumno*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Alumno*) (soff))->~G__TAlumno();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Mydict_160_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Alumno* dest = (Alumno*) G__getstructoffset();
   *dest = *(Alumno*) libp->para[0].ref;
   const Alumno& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Alumno */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncMydict {
 public:
  G__Sizep2memfuncMydict(): p(&G__Sizep2memfuncMydict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncMydict::*p)();
};

size_t G__get_sizep2memfuncMydict()
{
  G__Sizep2memfuncMydict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceMydict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableMydict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__MydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__MydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Alumno */
static void G__setup_memvarAlumno(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__MydictLN_Alumno));
   { Alumno *p; p=(Alumno*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->edad)-(long)(p)),105,0,0,-1,-1,-1,1,"edad=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nombre)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__MydictLN_string),-1,-1,1,"nombre=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarMydict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncAlumno(void) {
   /* Alumno */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__MydictLN_Alumno));
   G__memfunc_setup("Alumno",620,G__Mydict_160_0_1, 105, G__get_linked_tagnum(&G__MydictLN_Alumno), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Alumno",620,G__Mydict_160_0_2, 105, G__get_linked_tagnum(&G__MydictLN_Alumno), -1, 0, 2, 1, 1, 0, 
"i - - 0 - edad u 'string' - 0 - nombre", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ver",333,G__Mydict_160_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("Alumno", 620, G__Mydict_160_0_4, (int) ('i'), G__get_linked_tagnum(&G__MydictLN_Alumno), -1, 0, 1, 1, 1, 0, "u 'Alumno' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Alumno", 746, G__Mydict_160_0_5, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Mydict_160_0_6, (int) ('u'), G__get_linked_tagnum(&G__MydictLN_Alumno), -1, 1, 1, 1, 1, 0, "u 'Alumno' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncMydict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalMydict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcMydict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__MydictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__MydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__MydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__MydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MydictLN_Alumno = { "Alumno" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableMydict() {
  G__MydictLN_string.tagnum = -1 ;
  G__MydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__MydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__MydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MydictLN_Alumno.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableMydict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__MydictLN_string);
   G__get_linked_tagnum_fwd(&G__MydictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__MydictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MydictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MydictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__MydictLN_Alumno),sizeof(Alumno),-1,296192,(char*)NULL,G__setup_memvarAlumno,G__setup_memfuncAlumno);
}
extern "C" void G__cpp_setupMydict(void) {
  G__check_setup_version(30051515,"G__cpp_setupMydict()");
  G__set_cpp_environmentMydict();
  G__cpp_setup_tagtableMydict();

  G__cpp_setup_inheritanceMydict();

  G__cpp_setup_typetableMydict();

  G__cpp_setup_memvarMydict();

  G__cpp_setup_memfuncMydict();
  G__cpp_setup_globalMydict();
  G__cpp_setup_funcMydict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncMydict();
  return;
}
class G__cpp_setup_initMydict {
  public:
    G__cpp_setup_initMydict() { G__add_setup_func("Mydict",(G__incsetup)(&G__cpp_setupMydict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initMydict() { G__remove_setup_func("Mydict"); }
};
G__cpp_setup_initMydict G__cpp_setup_initializerMydict;

